# syntax=docker/dockerfile:1.2
# copied shamelessly from https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
# with edits to use pnpm fetch, cribbed from https://pnpm.io/cli/fetch
FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

RUN yarn global add pnpm@8.1.1
# Install dependencies based on the preferred package manager
COPY package.json pnpm-lock.yaml* ./
RUN pnpm fetch --prod
# RUN pnpm fetch --dev

ADD . ./
RUN pnpm install -r --offline
CMD ["pnpm", "dev"]