// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import (
	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// DbIFace is an autogenerated mock type for the DbIFace type
type DbIFace struct {
	mock.Mock
}

// GetConn provides a mock function with given fields:
func (_m *DbIFace) GetConn() *pgx.Conn {
	ret := _m.Called()

	var r0 *pgx.Conn
	if rf, ok := ret.Get(0).(func() *pgx.Conn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgx.Conn)
		}
	}

	return r0
}

type mockConstructorTestingTNewDbIFace interface {
	mock.TestingT
	Cleanup(func())
}

// NewDbIFace creates a new instance of DbIFace. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDbIFace(t mockConstructorTestingTNewDbIFace) *DbIFace {
	mock := &DbIFace{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
