// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/elonsoc/ods/backend/applications/types"
)

// DbIFace is an autogenerated mock type for the DbIFace type
type DbIFace struct {
	mock.Mock
}

// DeleteApplication provides a mock function with given fields: _a0
func (_m *DbIFace) DeleteApplication(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetApplication provides a mock function with given fields: _a0
func (_m *DbIFace) GetApplication(_a0 string) (types.Application, error) {
	ret := _m.Called(_a0)

	var r0 types.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (types.Application, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) types.Application); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.Application)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApplications provides a mock function with given fields:
func (_m *DbIFace) GetApplications() ([]types.Application, error) {
	ret := _m.Called()

	var r0 []types.Application
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]types.Application, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []types.Application); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Application)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewApp provides a mock function with given fields: _a0, _a1
func (_m *DbIFace) NewApp(_a0 string, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateApplication provides a mock function with given fields: _a0, _a1
func (_m *DbIFace) UpdateApplication(_a0 string, _a1 types.Application) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, types.Application) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDbIFace interface {
	mock.TestingT
	Cleanup(func())
}

// NewDbIFace creates a new instance of DbIFace. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDbIFace(t mockConstructorTestingTNewDbIFace) *DbIFace {
	mock := &DbIFace{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
