// Code generated by mockery v2.24.0. DO NOT EDIT.

package mocks

import (
	samlsp "github.com/elonsoc/saml/samlsp"
	mock "github.com/stretchr/testify/mock"
)

// SamlIFace is an autogenerated mock type for the SamlIFace type
type SamlIFace struct {
	mock.Mock
}

// GetSamlMiddleware provides a mock function with given fields:
func (_m *SamlIFace) GetSamlMiddleware() *samlsp.Middleware {
	ret := _m.Called()

	var r0 *samlsp.Middleware
	if rf, ok := ret.Get(0).(func() *samlsp.Middleware); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*samlsp.Middleware)
		}
	}

	return r0
}

type mockConstructorTestingTNewSamlIFace interface {
	mock.TestingT
	Cleanup(func())
}

// NewSamlIFace creates a new instance of SamlIFace. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSamlIFace(t mockConstructorTestingTNewSamlIFace) *SamlIFace {
	mock := &SamlIFace{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
