// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	statsd "github.com/smira/go-statsd"
)

// StatIFace is an autogenerated mock type for the StatIFace type
type StatIFace struct {
	mock.Mock
}

// Increment provides a mock function with given fields: _a0, _a1
func (_m *StatIFace) Increment(_a0 string, _a1 ...statsd.Tag) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// TimeElapsed provides a mock function with given fields: _a0, _a1
func (_m *StatIFace) TimeElapsed(_a0 string, _a1 int64) {
	_m.Called(_a0, _a1)
}

// NewStatIFace creates a new instance of StatIFace. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatIFace(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatIFace {
	mock := &StatIFace{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
