// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	samlsp "github.com/elonsoc/saml/samlsp"
)

// SamlIFace is an autogenerated mock type for the SamlIFace type
type SamlIFace struct {
	mock.Mock
}

// GetSamlMiddleware provides a mock function with given fields:
func (_m *SamlIFace) GetSamlMiddleware() *samlsp.Middleware {
	ret := _m.Called()

	var r0 *samlsp.Middleware
	if rf, ok := ret.Get(0).(func() *samlsp.Middleware); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*samlsp.Middleware)
		}
	}

	return r0
}

// NewSamlIFace creates a new instance of SamlIFace. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSamlIFace(t interface {
	mock.TestingT
	Cleanup(func())
}) *SamlIFace {
	mock := &SamlIFace{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
